apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: ecsdemo-nodejs
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: rancherdev 
    kind: SecretStore
  target:
    name: mysql-pwd
  data:
  - secretKey: teste 
    remoteRef:
      key: teste
      property: teste
