apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: rancherdev 
spec:
  provider:
    vault:
      server: "http://vault.wavy.global"
      path: "rancherdev"
      version: "v2"
      auth:
        # points to a secret that contains a vault token
        # https://www.vaultproject.io/docs/auth/token
        tokenSecretRef:
          name: "vault-token"
          namespace: "ecsdemo-nodejs"
          key: "token"
